Merge master in beta
auth0/auth0-spa-js pull request #1028
Opened 2022-10-20 16:23 UTC by ewanharris

### Changes

Updates beta with the latest changes in the master branch, including any changes required to the new examples file for the beta

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [x] All code quality tools/guidelines have been run/followed

2022-10-20 19:47 UTC, Widcket submitted a review, later dismissed

2022-10-24 11:31 UTC, frederikprijck requested changes

2022-10-24 11:31 UTC, frederikprijck commented on EXAMPLES.md
> +});
```suggestion
await createAuth0Client({
  domain: '<AUTH0_DOMAIN>',
  clientId: '<AUTH0_CLIENT_ID>',
  authorizationParams: {
    redirect_uri: '<MY_CALLBACK_URL>',
    organization: '<MY_ORG_ID>',
  }
});
```

2022-10-24 11:31 UTC, frederikprijck commented on EXAMPLES.md
> +```
We dont have anymore advanced options
```suggestion
```

2022-10-24 11:37 UTC, ewanharris commented on EXAMPLES.md
> +});
Fixed!

2022-10-24 13:16 UTC, merged