[SDK-2750] Expose mfa_token from the mfa_required error when getting new tokens
auth0/auth0-spa-js pull request #789
Opened 2021-09-06 13:22 UTC by frederikprijck

When mfa is enabled, the `/token` endpoint can return a `mfa_required` error. In the case that it does, it also included a `mfa_token` property, which we are currently ignoring.

This PR introduces a `MfaRequiredError` class that is used to unwrap the above information in case of a `mfa_required` error, exposing the `mfa_token` to the users.

2021-09-06 13:23 UTC, frederikprijck commented on src/http.ts
> +    json: { error, error_description, ...data },
Renamed this to data, because it contains the mfa_token and it was a bit weird to use `success` in case of `an error`.

2021-09-06 14:35 UTC, frederikprijck commented on src/errors.ts
> +    super(error, error_description) /* istanbul ignore next */;
Added a few istanbul ignores, see https://github.com/gotwarlost/istanbul/issues/690

2021-09-07 09:40 UTC, lbalmaceda approved these changes
LGTM

2021-09-07 10:47 UTC, stevehobbsdev requested changes
LG, just left a couple things around exports

2021-09-07 10:47 UTC, stevehobbsdev commented on src/errors.ts
> +export class MfaRequiredError extends GenericError {
Have you managed to test using this in a TypeScript app? I think we will need to export this error type here if we want to use it outside the library: https://github.com/auth0/auth0-spa-js/blob/cd3b1f9e9c88ce884251f8d1bb4b2550f70527a6/src/index.ts#L27-L33

2021-09-07 10:47 UTC, stevehobbsdev commented on src/errors.ts
> +export class MfaRequiredError extends GenericError {
And here: https://github.com/auth0/auth0-spa-js/blob/cd3b1f9e9c88ce884251f8d1bb4b2550f70527a6/src/index.cjs.ts#L1-L7

2021-09-08 16:06 UTC, stevehobbsdev approved these changes

2021-09-08 20:55 UTC, merged