[SDK-3541] Rework ignoreCache to cacheMode and introduce 'cache-only'.
auth0/auth0-spa-js pull request #950
Opened 2022-08-15 05:55 UTC by frederikprijck

### Changes

This PR reworks `ignoreCache` to use `cacheMode` instead, allowing for three `caching` modes.

- **on** (default): read from the cache caching, but fall back to Auth0 as needed
- **off**: don’t read from the cache
- **cache-only**: read from the cache, don’t fall back to Auth0

With the new `cache-only` option, we provide the user with the ability to try and retrieve a token from the cache, but not call Auth0 when there isn't any token to return, or the token is expired.

Users that used to use `ignoreCache: true`, should now use `cacheMode: 'off'` instead.

### Testing

- [x] This change adds unit test coverage
- [ ] This change adds integration test coverage
- [x] This change has been tested on the latest version of the platform/language

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [x] All code quality tools/guidelines have been run/followed

2022-08-15 12:47 UTC, ewanharris requested changes

2022-08-15 12:47 UTC, ewanharris commented on src/global.ts
> +   * When `only`, only reads from the cache and never sends a request to Auth0.
```suggestion
   * When `cache-only`, only reads from the cache and never sends a request to Auth0.
```

2022-08-15 12:47 UTC, ewanharris commented on src/global.ts
> +   * When `only`, only reads from the cache and never sends a request to Auth0.
```suggestion
   * When `cache-only`, only reads from the cache and never sends a request to Auth0.
```

2022-08-16 08:51 UTC, frederikprijck commented on src/global.ts
> +   * When `only`, only reads from the cache and never sends a request to Auth0.
```suggestion
   * When `cache-only`, only reads from the cache and never sends a request to Auth0.
```

2022-08-16 09:00 UTC, ewanharris approved these changes

2022-08-16 09:05 UTC, merged